# Generated by Django 4.2.18 on 2025-02-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
